apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqls.otus.homework # имя CRD должно иметь формат plural.group
spec:
  scope: Namespaced     # Данный CRD будер работать в рамках namespace
  group: otus.homework  # Группа, отражается в поле apiVersion CR
  versions:             # Список версий
    - name: v1
      served: true      # Будет ли обслуживаться API-сервером данная версия
      storage: true     # Фиксирует  версию описания, которая будет сохраняться в etcd
  versions:
    - name: v1
      served: true
      storage: true
      schema:        
        openAPIV3Schema: # openAPIV3Schema is the schema for validating custom objects.
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
              properties:
                name:
                  type: string
            spec:
              type: object
              properties:
                image: 
                  type: string
                database:
                  type: string
                password:
                  type: string
                storage_size:
                  type: string
              required: ["password", "image", "database", "storage_size"] #Список обязательных полей  

  names:                # различные форматы имени объекта CR
    kind: MySQL         # kind CR
    plural: mysqls      
    singular: mysql
    shortNames:
      - ms
