apiVersion: v1
kind: Pod
metadata:
  labels:
    run: frontend
  name: frontend
  namespace: default
spec:
  containers:
  - image: 3davinci/tinyweb:0.2
    imagePullPolicy: IfNotPresent
    name: frontend