apiVersion: v1
kind: Pod
metadata:
  name: web
  labels: 
    key: app

spec:
  containers:
  - name: web
    image: 3davinci/tinyweb:0.1
    imagePullPolicy: Always
    volumeMounts:
    - name: app      
      mountPath: /var/www/localhost/app
  initContainers:
  - name: init
    image: busybox:1.31.0
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:    
    - name: app
      mountPath: /app
  volumes:
  - name: app    
    emptyDir: {}
